### PR TITLE
Remove patch files that are no longer being applied.

### PR DESCRIPTION
**Pull request by greg-1-anderson**

### CODE REVIEW

**Comment by ari-gold** [comment]
Let's block this by CORE-2237 and bundle this with other changes we might make in the coming days and do a "release"

**Review by mbaynton — APPROVED** [review]
Good catch

**Comment by ari-gold** [comment]
Blocked by CORE-2237

**Comment by greg-1-anderson** [comment]
So back in the day we used to save up PRs for a release and try to pull them in when something else was going out. This turned out to be a nightmare, because it meant you had to resolve conflicts and worry about integration testing for multiple PRs at the same time you were doing a release.

What I recommend you do instead is make some other branch named perhaps "default", and merge all of your PRs into that branch. Then, when it's time to do a release, you only have to worry about overlaying the release on to one branch (default), test that, and then merge to master. Nightmare averted.

I'll let someone in #core decide when and how to push this out, though.

**Comment by mbaynton** [comment]
@greg-1-anderson Taking the above suggestion under advisement as well as the author requirement in `CORE-2237`, we're moving development activities to pantheon-systems/drupal-project. See https://github.com/pantheon-systems/drupal-project/pull/2 for details. TL;DR this PR has migrated to https://github.com/pantheon-systems/drupal-project/pull/3

**Pull request closed without merging**
